import Head from "next/head";
import { useQuery } from "react-query";
import React from "react";
import { useRouter } from "next/router";
import {
    fetchCreativeById,
} from "@/services/creatives";
import ArrowBack from "@mui/icons-material/ArrowBack";
import Image from "next/image";

const HomePage = () => {
    const { query, back } = useRouter();
    const { data, isLoading, error, isError } = useQuery(
        "creative",
        () => fetchCreativeById(query.creativeId as string),
        {

        }
    );
    if (isError) return <div className="main-white-box">{error as any}</div>;
    return (
        <>
            <Head>
                <title>Face ads</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="main-app">
                <div className="main-white-box-container">
                    <br />
                    <div className="row0">
                        <span style={{ cursor: "pointer" }} onClick={() => back()}>
                            {" "}
                            <ArrowBack />
                        </span>
                        <h2>Detalhes do criativo {!!data?.asset_feed_spec ? '[VIDEO]' : ''}</h2>
                        <span />
                    </div>

                    <br />
                    <div className="center">
                        {!data?.asset_feed_spec && (
                            <>
                                <span style={{ width: '80%' }}>{data?.body}</span>
                                <br />
                                {!isLoading && (
                                    <Image
                                        width={350}
                                        height={350}
                                        loading={"lazy"}
                                        alt={data?.name as string}
                                        src={(data?.image_url ?? data?.thumbnail_url) as string}
                                    />
                                )}
                                <br />
                                <span>{data?.title}</span>
                            </>
                        )}
                        {data?.asset_feed_spec &&(
                            <>
                            <span style={{width: '80%'}}>{data?.asset_feed_spec?.bodies[0].text}</span>
                            <br/>
                            {!isLoading && (
                                    <Image
                                        width={350}
                                        height={350}
                                        loading={"lazy"}
                                        alt={data?.name as string}
                                        src={(data?.image_url ?? data?.thumbnail_url) as string}
                                    />
                                )}
                                        <br />
                                <span>{data?.asset_feed_spec.titles[0].text}</span>
                            </>
                        )}
                    </div>
                </div>
            </main>

            <div
                style={{ display: isLoading ? "flex" : "none" }}
                className={"loader"}
            />
        </>
    );
};

export default HomePage;
